### ISSUE TITLE
Failed to locate image 

### ISSUE THREAD

**Issue by dixonsiu** [molavec/aircv-hexo-theme#2]
When hero.yaml is copied from "themes\aircv\source\\_default_data" to "source\\_data", the following error occurs. However, other yaml files do not have the same problem. 
```
---
WARN: Image not found:
/mnt/d/.../hexo/myblog/themes/aircv/scripts/../../../source/img/1920x1080/01.jpg
Use 'npm -i --save hexo-filter-responsive-images' and type 'hexo generate' again to get responsive images.
---
```

**Comment by molavec** [comment]
Hi @dixonsiu 

1.- the folder should be **./source/_data**, not **source_data**. (I guest do you type bad, but anyway I note that)
2.- Remember install theme dependencies. (hexo-filter-responsive-images in your main package.json). 
```bash
$ yarn add hexo-renderer-scss hexo-filter-responsive-images imageinfo js-yaml
```

I think, the second one could cause the problem.

Let me know if some of this solve problem.

**Comment by dixonsiu** [comment]
Hi @molavec 
Thank you for replying. I did copy to the "source\\_data" folder and execute the yarn add command.
Isn't the access target be "/mnt/d/.../hexo/myblog/themes/aircv/scripts/../../../public/img/1920x1080/01.jpg" or am I supposed to copy all the folders in "themes/aircv/source" to "source"

**Comment by molavec** [comment]
Hi @dixonsiu, I guess it because the image "myblog/source/img/1920x1080/01.jpg" is not present  image (Hero or main image) in your "myblog/source/img/" folder. The build use source data instead theme default source when is present so, I recommend copy all source and modify from this copy.

Consider that this theme use "hexo-filter-responsive-images" filter plugin to auto generate og: opengraph images to help whatsapp sharing image and descriptions.

**Edit:**
Note that /source/_data/hero.yaml has options that you could modify (every files in /source/_data, should customize)
This is my custom hero, so I need correctly assets in my source folder.
```yaml
title: "Miguel<br>Olave"
proposal_value: "Desarrollador &amp; UX Project Manager"
image: "img/hero.jpg"
```
and results it is here:
https://molavec.com

**Comment by dixonsiu** [comment]
Thank you very much @molavec !
